{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rclone-s3-operator.fullname" . }}
  labels:
    {{- include "rclone-s3-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["storage.max.io"]
    resources: ["buckets", "buckets/status", "buckets/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "secrets", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rclone-s3-operator.fullname" . }}
  labels:
    {{- include "rclone-s3-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rclone-s3-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rclone-s3-operator.fullname" . }}
{{- end }}
